language: python
sudo: required
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev
  - sudo apt-get install python-pip
install:
  - python -m pip install --upgrade pip
  - pip install setuptools
  - pip install .
script:
  - peid --help
